### ISSUE TITLE
example deployWorkflow.js crashes

### ISSUE THREAD

**Issue by Zhami** [zeebe-io/zbc-node#21]
I am very new to Zeebe, so this error may be mine... I have the Zebee Broker running via Docker and it seems fine, reports healthy messages such as:

> 18:41:11.250 [workflow-instance] [172.17.0.2:26501-zb-fs-workers-0] INFO  io.zeebe.logstreams - Write snapshot for stream processor workflow-instance at event position -1.
> 18:41:11.251 [workflow-instance] [172.17.0.2:26501-zb-fs-workers-0] INFO  io.zeebe.logstreams - Creation of snapshot workflow-instance took 1 ms.

When I run the node code for the deployWorkflow.js example, the code crashes when zbClient.createWorkflow is invoked:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x106964821]
> 
> goroutine 17 [running, locked to thread]:
> main.CreateWorkflow(0x103306e10, 0xb, 0x103306e80, 0x12, 0x106853386)
> 	/go/src/github.com/zeebe-io/libzbc/main.go:68 +0xd1
> main._cgoexpwrap_52cba5f19b0c_CreateWorkflow(0x103306e10, 0xb, 0x103306e80, 0x12, 0x0)
> 	_cgo_gotypes.go:97 +0x7c

I observe that the creation of the zbClient takes a "long" time (sorry, have not measured). Ah, I just noticed in the console that there is a message:

> Error connecting to client with given bootstrap Address: 0.0.0.0:51015

So, is there a way to evaluate the zbClient instance generated by `new Client()` to detect this failure in code?

Even if there is a connection error, I suggest that the module fail gracefully rather than die with a panic.

I am running Node version v10.11.0 on a Mac.

I installed with npm. Not sure if this is important, but there were many warnings issued by the compiler.

I'd appreciate any guidance to get the Node client running - Zeebe looks fantastic to me and I want to sell my management with a demo.

**Comment by Zhami** [comment]
I notice that the ports used by the system in the container are all in the 26500 range, with the client service at 26501. So I restarted the system in docker by exposing 26501:
`docker run --name zeebe -p 26501:26501 camunda/zeebe:latest`
And also changed the `bootstrapAddr` of the `new Client()` call to match. 
I still can't get a connection.
Also... I am unsure what a "bootstrap address" is... would that be something other than the client port?

**Comment by Zelldon** [comment]
Hi @Zhami thanks for the report.

Unfortunately the zbc-node was currently not ported and does not work with the latest Zeebe version.
I think since 0.11.0 it was not updated. As it is a community project, we can't guarantee when it will be updated. Please take a look on the official supported grpc Clients

**Comment by Zhami** [comment]
Thank you for the fast reply. I had seen the documents you referenced but then stumbled upon this zbc-node client and was very enthused as Javascript is my language of choice. 

Is updating the zbc-node client to run with latest Zeebe on your Roadmap?

**Comment by menski** [comment]
Hi @Zhami,

currently we do not plan to create a new node.js client in the immediate future. But with the new gRPC protocol you have the possibility to easily create your own javascript client. You can have a look at https://github.com/grpc/grpc-node and https://github.com/grpc/grpc-web.

Our protocol specification can be found at https://github.com/zeebe-io/zeebe/blob/master/gateway-protocol/src/main/proto/gateway.proto

I personally played around with `grpc-web` today and was able to create a new workflow instance with these few lines of code, using the generated gRPC stubs.

```
const {CreateWorkflowInstanceRequest, CreateWorkflowInstanceResponse} = require('./gateway_pb.js');
const {GatewayClient} = require('./gateway_grpc_web_pb.js');

var client = new GatewayClient('http://' + window.location.hostname + ':8081');

$("#createInstance").click(function(e) {
    e.preventDefault();
    var request = new CreateWorkflowInstanceRequest();
    request.setBpmnprocessid($('#bpmnId').val());
    request.setPayload($('#payload').val());
    client.createWorkflowInstance(request, {}, (err, response) => {
        if (err != null) {
            console.log(err);
        } else {
            alert('Created workflow instance with key: ' + response.getWorkflowinstancekey());
        }
    });
});
```

I'm happy to support you if you have more questions or want to try to build something with the gRPC stubs.

Cheesrs,
Sebastian

**Comment by Zhami** [comment]
Thank you, Sebastian, for the suggestion. I will explore.
